version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_toolbox_development
    ports:
      - "3307:3306"
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - ./:/rails_toolbox
    ports:
        - "3000:3000"
    depends_on:
      - db
    links:
      - db
